### ISSUE TITLE
NoSaveBuffer is slow

### ISSUE THREAD

**Issue by EtienneBruines** [jadref/buffer_bci#11]
I noticed the `NoSaveBuffer` being really, really slow. 

When issuing the `GET_DAT` command, I'm measuring the time it takes to read the number of channels from the buffer (so not the actual data yet). The Java buffer was roughly 100000 times faster (in the range of nanoseconds, instead of 40 ms). 

As the NoSaveBuffer is written in C, I think there's a bug somewhere that needs to be fixed. 

Doing a quick lookup in the code, the "bug" should be somewhere here: https://github.com/jadref/buffer_bci/blob/a9570657c25b3d9971e47cb22d78f397d9656dcb/dataAcq/buffer/c/dmarequest.c#L359-L506

**Comment by bcicourse** [comment]
Hi,

Can I ask a couple of clarifying questions.
1) what OS are you using?
2) Is it still slow when you write a large data-packet of > 2k in size?

The reason I ask is that previously we have noticed that some OS's delay
TCP messages smaller than a threshold size to improve network performance
(Nagels algorithm), and the normal delay is ~40ms....

Jason

On Tue, Dec 8, 2015 at 2:59 PM, Etienne Bruines <notifications@github.com>
wrote:

> I noticed the NoSaveBuffer being really, really slow.
>
> When issuing the GET_DAT command, I'm measuring the time it takes to
> write the number of channels (so not the actual data yet). The Java buffer
> was roughly 100000 times faster (in the range of nanoseconds, instead of 40
> ms).
>
> As the NoSaveBuffer is written in C, I think there's a bug somewhere that
> needs to be fixed.
>
> Doing a quick lookup in the code, the "bug" should be somewhere here:
> https://github.com/jadref/buffer_bci/blob/a9570657c25b3d9971e47cb22d78f397d9656dcb/dataAcq/buffer/c/dmarequest.c#L359-L506
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jadref/buffer_bci/issues/11>.
>



-- 
Dr. Jason Farquhar
http://www.dcc.ru.nl/~jdrf                 jdrf@zepler.org
Dept. Cognitive Artificial Intelligence              Tel:(+31)2436 11938
Donders Institute for Brain, Cognition and Behaviour
Rm. B 00.94, Montessorilaan 3, 6525 HR Nijmegen      Fax:(+31)2436 16066
------------------------------------------------------------------------
   "There is no more dangerous error than that of mistaking the
effect for the cause: I call it the real corruption of reason."

-Friedrich Nietzsche (1844-1900), Twilight of the Idols

**Comment by Damacustas** [comment]
Doesn't calling flush() on a socket (partially) circumvent Nagels algorithm?

**Comment by EtienneBruines** [comment]
Hi,

1) I'm using Linux (64bit), newest kernel (4.2.6-1)
2) I'm not sure how to test this; it's not slow when calling `WAIT_DAT`, which is also < 2k in size - does that help?

I haven't been able to figure out if the NoSaveBuffer is compiled with the Nagels algorithm [turned off](https://github.com/jadref/buffer_bci/blob/a9570657c25b3d9971e47cb22d78f397d9656dcb/dataAcq/buffer/c/socketserver.c#L453), or turned on. 

From what I've read, `flush()` should indeed be able to circumvent that. Setting `echo 1 > /proc/sys/net/ipv4/tcp_low_latency` did not fix the problem. I'm now trying to recompile the buffer with `TCP_NODELAY`, but I'm not sure how to get from the object files, to an actual (executable) binary file inside `buffer/glnx86/buffer`

**Comment by bcicourse** [comment]
Hi,

This does indeed sound like a nagel's algorithm issue.

The source code already contains a compile time option to disable this for
buffer connections, using the -DDISABLE_NAGEL option.  I have added the
code for the buffer server to the dataAcq/buffer/c directory and modified
the make-file so it will make it automatically and put it in the correct
location.  (Though you may still need to modify for 64-bit).  You should be
able to build it fine this way now.

(BTW: Generally we currently perfer and advise to use the java-buffer, as
the code is more widely used and maintained at the moment.)

(BTW2: The buffer code is actually from the fieldtrip real-time system <
http://www.fieldtriptoolbox.org/development/realtime>.  If ou think this is
a real issue - i.e. you need a bug-fix fror the source code, then I would
advise to file a bug there also.)

Jason

On Tue, Dec 8, 2015 at 11:24 PM, Etienne Bruines <notifications@github.com>
wrote:

> Hi,
>
> 1) I'm using Linux (64bit), newest kernel (4.2.6-1)
> 2) I'm not sure how to test this; it's not slow when calling WAIT_DAT,
> which is also < 2k in size - does that help?
>
> I haven't been able to figure out if the NoSaveBuffer is compiled with the
> Nagels algorithm turned off
> <https://github.com/jadref/buffer_bci/blob/a9570657c25b3d9971e47cb22d78f397d9656dcb/dataAcq/buffer/c/socketserver.c#L453>,
> or turned on.
>
> From what I've read, flush() should indeed be able to circumvent that.
> Setting echo 1 > /proc/sys/net/ipv4/tcp_low_latency did not fix the
> problem. I'm now trying to recompile the buffer with TCP_NODELAY, but I'm
> not sure how to get from the object files, to an actual (executable) binary
> file inside buffer/glnx86/buffer
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jadref/buffer_bci/issues/11#issuecomment-163037174>.
>



-- 
Dr. Jason Farquhar
http://www.dcc.ru.nl/~jdrf                 jdrf@zepler.org
Dept. Cognitive Artificial Intelligence              Tel:(+31)2436 11938
Donders Institute for Brain, Cognition and Behaviour
Rm. B 00.94, Montessorilaan 3, 6525 HR Nijmegen      Fax:(+31)2436 16066
------------------------------------------------------------------------
   "There is no more dangerous error than that of mistaking the
effect for the cause: I call it the real corruption of reason."

-Friedrich Nietzsche (1844-1900), Twilight of the Idols
