### ISSUE TITLE
Matrix Speller Feedback Question.

### ISSUE THREAD

**Issue by mlearnx** [jadref/buffer_bci#12]
Hi there, 
Thanks a lot for sharing the buffer_bci. We were working on P300 based Matrix Speller. 

By running the examples of spellers both Matlab and Psychtoolbox ones; we noticed that the result of the recognized letters are highlighted on a speller grid. 

We were wondering if it is possible to have a **separate window** to display the mental typing as in OpenVibe examples. Your help is very much appreciated. 

Thank you again,
John.

**Comment by jadref** [comment]
Hi John,

Thanks for your interest in buffer_bci.

I'm not quite sure I understand your question... but I'll give a stab at an answer.
If you want to display the total sentence so far in a separate window, then the easiest way would be to catch the 'stimulus.prediction' events, which contain the predicted letter, i.e. the one that is highlighted in green.  Then you can do whatever you want with these predictions.
Catching the events is pretty simple, e.g. in matlab, logic is similar in python,java etc.

configureSpeller; % setup paths, connect to buffer_server, etc..
state=[]; % initial state
while (true)
   [pevents,state]=buffer_newevents(buffhost,buffport,state,'stimulus.prediction');
   if ( ~isempty(pevents) ) 
      predSymb = pevents(end).value;
     % now do something with this prediction, e.g. show it on the screen
   end
end

**Comment by mlearnx** [comment]
Hi Jadref,

Appreciate your taking the time to explain the steps.  Now I see it can be done easily. 
It's a great toolbox indeed. Let us also know how to cite it at your earliest convenience.  

Best regards,
John.

**Comment by jadref** [comment]
Hi John,

No problem, good luck making it all work.

For citation it's not in a paper or so as yet, so the simplist way to cite would be via a link to the git-hub page.

Jason
